### ISSUE TITLE
Invalid dependencies options (must be a string or array of strings)

### ISSUE THREAD

**Issue by iostat42** [johnbrett/calibrate#3]
Tests fail when I tried updating dependencies.  I fixed locally and I will submit a pull request shortly.

````
Failed tests:

  11) Calibrate decorates the hapi reply interface:

      Invalid dependencies options (must be a string or an array of strings) {
  "boom": "~2.6.x",
  "code": "^1.3.0",
  "isdefined": "~1.x.x",
  "0" [1]: -- missing --
}

[1] "0" must be a string

    "boom": "~2.6.x",
    "code": "^1.3.0",
    "isdefined": "~1.x.x",
    "0" [1]: -- missing --
  }
  
  [1] "0" must be a string
      at Object.exports.assert (/Users/brian/Documents/dev/nodejs/dev/calibrate_clean/calibrate/node_modules/hapi/node_modules/hoek/lib/index.js:723:11)
      at Object.exports.assert (/Users/brian/Documents/dev/nodejs/dev/calibrate_clean/calibrate/node_modules/hapi/lib/schema.js:15:10)
      at internals.Plugin.register (/Users/brian/Documents/dev/nodejs/dev/calibrate_clean/calibrate/node_modules/hapi/lib/plugin.js:231:16)
      at /Users/brian/Documents/dev/nodejs/dev/calibrate_clean/calibrate/test/index.js:112:12
      at Immediate._onImmediate (/Users/brian/Documents/dev/nodejs/dev/calibrate_clean/calibrate/node_modules/lab/lib/runner.js:453:17)
      at processImmediate [as _immediateCallback] (timers.js:358:17)
````

**Comment by johnbrett** [comment]
Closed via https://github.com/johnbrett/calibrate/issues/4. Thank you for this @iostat42! Took my eye off the ball here, will try keep more up to date in future. If you have any feature requests for Calibrate please let me know :)
